# Generated by Django 3.2.9 on 2021-11-30 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AeStrategy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("description", models.TextField()),
                ("enum", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="AntiflickerAttr",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("description", models.TextField()),
                ("enum", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="AntiFogAttr",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("description", models.TextField()),
                ("enum", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="ColorfxMode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("description", models.TextField()),
                ("enum", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="CoreAwbStatsMode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("description", models.TextField()),
                ("enum", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="CoreExposureMode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("description", models.TextField()),
                ("enum", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="CoreExposureUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("description", models.TextField()),
                ("enum", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="CoreWhiteBalanceMode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("description", models.TextField()),
                ("enum", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="DrcMode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("description", models.TextField()),
                ("enum", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="MeshShadingScale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("description", models.TextField()),
                ("enum", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="RunningMode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("description", models.TextField()),
                ("enum", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="SceneMode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("description", models.TextField()),
                ("enum", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="TemperMode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("description", models.TextField()),
                ("enum", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="TuningMode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("description", models.TextField()),
                ("enum", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="TuningOpsMode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("description", models.TextField()),
                ("enum", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="TuningOpsType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("description", models.TextField()),
                ("enum", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="CameraProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ae_strategy",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="openmiko.aestrategy",
                    ),
                ),
                (
                    "anti_flicker_attr",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="openmiko.antiflickerattr",
                    ),
                ),
                (
                    "anti_fog_attr",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="openmiko.antifogattr",
                    ),
                ),
                (
                    "color_fx_mode",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="openmiko.colorfxmode",
                    ),
                ),
                (
                    "core_awb_stats_mode",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="openmiko.coreawbstatsmode",
                    ),
                ),
                (
                    "core_exposure_mode",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="openmiko.coreexposuremode",
                    ),
                ),
                (
                    "core_exposure_unit",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="openmiko.coreexposureunit",
                    ),
                ),
                (
                    "core_white_balance_mode",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="openmiko.corewhitebalancemode",
                    ),
                ),
                (
                    "drc_mode",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="openmiko.drcmode",
                    ),
                ),
                (
                    "mesh_shading_scale",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="openmiko.meshshadingscale",
                    ),
                ),
                (
                    "running_mode",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="openmiko.runningmode",
                    ),
                ),
                (
                    "scene_mode",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="openmiko.scenemode",
                    ),
                ),
                (
                    "temper_mode",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="openmiko.tempermode",
                    ),
                ),
                (
                    "tuning_mode",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="openmiko.tuningmode",
                    ),
                ),
                (
                    "tuning_ops_mode",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="openmiko.tuningopsmode",
                    ),
                ),
            ],
        ),
    ]
